# Generated by Django 5.2.6 on 2025-09-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_maintenancerequestattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Nombre del Propietario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Acceso Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
