# Generated by Django 4.2.26 on 2025-12-16 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_authorizedvehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('document_id', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(upload_to='visitors/')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_authorized', models.BooleanField(default=False)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_visitors', to=settings.AUTH_USER_MODEL)),
                ('visiting_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='core.unit')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('UNAUTHORIZED_PERSON', 'Persona No Autorizada'), ('LOOSE_PET', 'Mascota Suelta'), ('PET_WASTE', 'Mascota Haciendo Necesidades'), ('WRONG_PARKING', 'Vehículo Mal Estacionado'), ('SUSPICIOUS_BEHAVIOR', 'Comportamiento Sospechoso'), ('UNAUTHORIZED_VEHICLE', 'Vehículo No Autorizado'), ('OTHER', 'Otro')], max_length=30)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incidents/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, help_text='Ubicación del incidente', max_length=200)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Nivel de confianza de la IA (0-1)')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_data', models.TextField(help_text='Encoding facial en formato JSON')),
                ('photo', models.ImageField(help_text='Foto de referencia', upload_to='face_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_encodings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('FACIAL', 'Reconocimiento Facial'), ('VEHICLE', 'Reconocimiento Vehicular'), ('MANUAL', 'Manual'), ('VISITOR', 'Visitante')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='access_logs/')),
                ('was_granted', models.BooleanField(default=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='core.visitor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
