# Generated by Django 4.2.26 on 2025-12-17 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_notice_viewed_by_visitor_securityincident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('USER_LOGIN_SUCCESS', 'Inicio de sesión exitoso'), ('USER_LOGOUT_MANUAL', 'Cierre de sesión manual'), ('USER_LOGOUT_EXPIRED', 'Cierre de sesión por expiración'), ('PAGE_ACCESS', 'Acceso a página'), ('CREATE', 'Creación de registro'), ('UPDATE', 'Actualización de registro'), ('DELETE', 'Eliminación de registro'), ('PAYMENT_CREATED', 'Pago creado'), ('RESERVATION_CREATED', 'Reservación creada'), ('MAINTENANCE_REQUEST', 'Solicitud de mantenimiento'), ('NOTICE_PUBLISHED', 'Aviso publicado'), ('PROFILE_UPDATED', 'Perfil actualizado'), ('PASSWORD_CHANGED', 'Contraseña cambiada'), ('AI_FACE_RECOGNITION', 'Reconocimiento facial'), ('AI_VEHICLE_RECOGNITION', 'Reconocimiento de vehículo'), ('AI_VISITOR_REGISTERED', 'Visitante registrado con IA'), ('AI_ANOMALY_DETECTED', 'Anomalía detectada'), ('SECURITY_INCIDENT', 'Incidente de seguridad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-timestamp'], name='core_activi_timesta_8baae3_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-timestamp'], name='core_activi_user_id_d7adda_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='core_activi_action_b2beff_idx'),
        ),
    ]
