# Generated by Django 4.2.26 on 2025-12-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_activitylog_description_activitylog_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
